# Configuration file for Paper Summarizer
openai_api_key: "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"
papers_directory: "./papers" 
output_directory: "./output"
