# Configuration file for Paper Summarizer

#Folder directories
papers_directory: "./papers" 
output_directory: "./output"

#API keys
OPENAI_API_KEY: 
NCBI_API_KEY: 

search_query: ("Artificial intelligence"[Title/Abstract] OR "machine learning"[Title/Abstract] AND "Protein-protein interaction")

meta_data: 

    - data_type: Type of data used in the study such as radiology, clinicopathologic, or text
    - species_breed: Target species
    - ml_algorithm: Types Model used in the study
    - ai_goal: Clinical objective of the study
    - performance_results: Key final performance results


in_depth: 
        
    - small_dataset: Short explanation if fewer than ~1000 samples OR authors mention limited data. Infer from methods if possible, else return unknown.
   
        

        

